name: flake8

on: push

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: flake8
    steps:
      - name: Check out source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: flake8
        uses: julianwachholz/flake8-action@v2
        with:
          plugins: flake8-spellcheck
          config: pyproject.toml
