name: flake8

on: push

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: flake8
    steps:
      - name: Check out source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: flake8
        run: |
          pip install flake8
          flake8 --exit-zero .
