name: Testing
on: push
jobs:
  build-and-test:
    name: Testing using ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    # run pipeline on either a push event or a PR event on a fork
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest
        run: |
          pip install pytest
          pip install pytest-cov
      - name: Install package
        run: pip install -e .
      - name: Run pytest with coverage
        run: pytest --cov=./ --cov-report xml:./nwbinspector/nwbinspector/coverage.xml
      - if: ${{ matrix.python-version == "3.8" && matrix.os == "ubuntu-latest" }}
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          file: ./nwbinspector/nwbinspector/coverage.xml
          flags: unittests
